# Generated by Django 6.0.6 on 2026-06-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pet_type',
            field=models.CharField(choices=[('cat', 'Кошка'), ('dog', 'Собака'), ('bird', 'Птица')], default='cat', max_length=30),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('Cat', 'Кошка'), ('Dog', 'Собака'), ('Bird', 'Птица')], max_length=25),
        ),
    ]
