# Generated by Django 6.0.6 on 2026-06-27 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pet_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='main.pet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_recommendations', to='main.product')),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('pet', 'product')},
            },
        ),
    ]
