# Generated by Django 6.0.6 on 2026-07-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_petrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='repeat_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='repeat_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
